name: ppg-speech
channels:
  - pytorch
  - pykaldi
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2019.5.15=1
  - certifi=2019.6.16=py37_1
  - libtiff=4.0.10=h2733197_2
  - olefile=0.46=py37_0
  - openssl=1.1.1l=h7f98852_0
  - pillow=6.1.0=py37h34e0f95_0
  - zstd=1.3.7=h0b5b093_0
  - audioread=2.1.6=py37_0
  - blas=2.12=openblas
  - bzip2=1.0.8=h516909a_0
  - cffi=1.12.3=py37h8022711_0
  - cycler=0.10.0=py_1
  - dbus=1.13.6=he372182_0
  - decorator=4.4.0=py_0
  - expat=2.2.5=he1b5a44_1003
  - ffmpeg=4.2=h167e202_0
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.0=he983fc9_1
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=h6f030ca_1002
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.6.5=hd3a4fd2_1002
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - icu=58.2=hf484d3e_1000
  - joblib=0.13.2=py_0
  - jpeg=9c=h14c3975_1001
  - kiwisolver=1.1.0=py37hc9558a2_0
  - lame=3.100=h14c3975_1001
  - libblas=3.8.0=12_openblas
  - libcblas=3.8.0=12_openblas
  - libffi=3.2.1=he1b5a44_1006
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=12_openblas
  - liblapacke=3.8.0=12_openblas
  - libopenblas=0.3.7=h6e990d7_1
  - libpng=1.6.37=hed695b0_0
  - librosa=0.6.2=py_0
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_2
  - llvmlite=0.29.0=py37hfd453ef_1
  - ncurses=6.1=hf484d3e_1002
  - nettle=3.4.1=h1bed415_1002
  - ninja=1.9.0=h6bb024c_0
  - nose=1.3.7=py37_2
  - numba=0.45.1=py37hb3f55d8_0
  - openblas=0.3.7=h6e990d7_1
  - openh264=1.8.0=hdbcaa40_1000
  - pcre=8.41=hf484d3e_1003
  - pip=19.2.3=py37_0
  - pthread-stubs=0.4=h14c3975_1001
  - pycparser=2.19=py37_1
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py37hcca6a23_4
  - python-dateutil=2.8.0=py_0
  - pytz=2019.2=py_0
  - qt=5.9.7=h52cfd70_2
  - readline=7.0=hf8c457e_1001
  - resampy=0.2.2=py_0
  - scikit-learn=0.21.3=py37hcdab131_0
  - setuptools=41.2.0=py37_y
  - sip=4.19.8=py37hf484d3e_1000
  - six=1.12.0=py37_1000
  - sqlite=3.28.0=h8b20d00_0
  - tensorboardx=1.2=py_0
  - tk=8.6.9=hed695b0_1002
  - tornado=6.0.3=py37h516909a_0
  - wheel=0.33.6=py37_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h14c3975_1001
  - zlib=1.2.11=h516909a_1005
  - _libgcc_mutex=0.1=main
  - coverage=4.5.2=py37h7b6447c_0
  - intel-openmp=2019.4=243
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libprotobuf=3.6.1=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - matplotlib=3.0.2=py37h5429711_0
  - mkl=2019.4=243
  - numpy=1.15.4=py37h99e49ec_0
  - numpy-base=1.15.4=py37h2f8d375_0
  - protobuf=3.6.1=py37he6710b0_0
  - python=3.7.2=h0371630_0
  - scipy=1.1.0=py37he2b7bc3_2
  - pykaldi=0.1.0=py37h82fe3e7_1
  - cuda80=1.0=h205658b_0
  - pytorch=1.0.0=py3.7_cuda8.0.61_cudnn7.1.2_1
  - pip:
    - textgrid==1.4
    - torch==1.0.0
prefix: /home/guanlong/anaconda2/envs/ppg-speech

